### ISSUE TITLE
USB定制问题

### ISSUE THREAD

**Issue by hanxi2719** [lynnlin9301/hackintosh#4]
你好，我发现网口下面的两个USB3.0的口无法使用，红色框中的是可以使用的，请帮忙确认下你那边是否OK，多谢！
<img width="1092" alt="截屏2020-02-15下午3 56 42" src="https://user-images.githubusercontent.com/35458937/74584324-175caa80-500c-11ea-9aa6-968659d08e52.png">

**Comment by lynnlin9301** [comment]
我这都能用啊。
你用 hackintool 看下。
在我的 EFI 上，对应的是 SS04 - 0X14 和 SS06-0X16 
![image](https://user-images.githubusercontent.com/19951387/74584396-c9947200-500c-11ea-8d32-2153ef396216.png)

如果你有自己插前置面板的usb，你需要自己改一下DSDT，请参考 readme 里面最后附上的黑果小兵论坛的文章。

我没有用前置usb 是因为，我电脑的摆放角度，刚好是后面板冲着我的。所以前面的我反而没接。

**Comment by lynnlin9301** [comment]
你可以先用 1.0.0 标签的代码。然后自己定制 DSDT
因为我的使用环境比较，可能和一般人不太一样。
我所有的键盘和鼠标，都是蓝牙链接，并且，我没有从主板针口上，外接任何的音频、USB 设备。

1.0.0 和 1.0.1 的区别就是以下内容
- 改了DSDT，这个建议你用通用的 USBinject 自己修改适合自己的电脑的，以解决可能存在的自动唤醒问题。
- 精简了不必要的 config 内容。我把这个 config 里面多余的都删了。理论上来说，你不删应该也没啥影响。

其他基本没有改变。

**Comment by hanxi2719** [comment]
> 我这都能用啊。
> 你用 hackintool 看下。
> 在我的 EFI 上，对应的是 SS04 - 0X14 和 SS06-0X16
> ![image](https://user-images.githubusercontent.com/19951387/74584396-c9947200-500c-11ea-8d32-2153ef396216.png)
> 
> 如果你有自己插前置面板的usb，你需要自己改一下DSDT，请参考 readme 里面最后附上的黑果小兵论坛的文章。
> 
> 我没有用前置usb 是因为，我电脑的摆放角度，刚好是后面板冲着我的。所以前面的我反而没接。

很奇怪，我的不可以，我截图给你看。
<img width="664" alt="截屏2020-02-15下午5 28 27" src="https://user-images.githubusercontent.com/35458937/74585558-abcd0a00-5018-11ea-9fd2-8335f92e8f02.png">

**Comment by lynnlin9301** [comment]
你的端口数量太多了 。
你要定制的话，USB端口数量不能超过15个。
- USB 3.0 算2个。
- USB2.0 算1个。
- internal 没有找到明确的数量说是1个还是2个。为了避免问题，我个人设置时，默认认为 internal 占用2个端口。

两种方案。
1. 你要么不定制DSDT，选择破解数量的。
2. 要么你定制DSDT，将部分 USB3.0  降级为USB2.0 处理，保持端口数量在15个以内。

参考：
- https://blog.daliansky.net/Intel-FB-Patcher-USB-Custom-Video.html
- https://zhuanlan.zhihu.com/p/68338188

**Comment by hanxi2719** [comment]
好的 多谢，你的EFI很棒，温度传感器很详细，用的很好，USB这个不影响使用，我也不会，哈哈，就这么用了，还是得感谢你。
<img width="240" alt="截屏2020-02-15下午5 47 41" src="https://user-images.githubusercontent.com/35458937/74585758-47f81080-501b-11ea-9084-bbaba5943401.png">

**Comment by lynnlin9301** [comment]
客气了。共同学习交流。
